version: "2.4"

services:
    nginx:
        build:
            context: .
            dockerfile: Dockerfile.nginx
        image: dns/nginx:latest
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - dns

    dns:
        build:
            context: .
            dockerfile: Dockerfile.dns
        image: dns/dns:latest
        ports:
            - "53:53/udp"
        environment:
            - PUB_IP
            - PYTHONUNBUFFERED=0
